name: sync-releases-biblequiz
on:
  workflow_dispatch:
  release:
    types: [created, edited, deleted, prereleased, published, released, unpublished]
jobs:
  sync-release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "release action=${{ github.event.action }}"
