name: Sync Release Changes to BibleQuiz.com

on:
  release:
    types: [published, created, prereleased, edited, unpublished, deleted]

jobs:
  sync-release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "action=${{ github.event.action }} name=${{ github.event.release.name }}"
